services:
  mysql:
    image: mysql:8.0           # 8.0.36 as of July 2025, arm64 build included
    container_name: mysqlp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
      MYSQL_USER: psuser
      MYSQL_PASSWORD: pspass
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [prestanet]

  prestashop:
    image: prestashop/prestashop:8.1
    container_name: prestashopp
    restart: always
    depends_on: [mysql]
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: psuser
      DB_PASSWD: pspass
      PS_DEV_MODE: "1"                # Symfony debug toolbar etc.
      PS_INSTALL_AUTO: "1"            # unattended install
      PS_DOMAIN: localhost:8080       # first host/port to store
      PS_HANDLE_DYNAMIC_DOMAIN: "1"   # self-heals if you change host/port
    ports:
      - "8080:80"
    volumes:
      - prestashop_data:/var/www/html
    networks: [prestanet]
    platform: "linux/amd64"           # PrestaShop image is x86-64-only

volumes:
  mysql_data:
    driver: local
  prestashop_data:
    driver: local

networks:
  prestanet:
    driver: bridge

