version: "3.9"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    volumes: [ dbdata:/var/lib/mysql ]

  prestashop:
    image: prestashop/prestashop:8.1   # bump this tag to upgrade :contentReference[oaicite:1]{index=1}
    depends_on: [ db ]
    ports: [ "8080:80" ]
    environment:
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
    volumes:
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
      - shopdata:/var/www/html         # persistent uploads

volumes:
  dbdata:
  shopdata:
